//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderItemsWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Distributor
    {
        public string DistributorID { get; set; }
        public string DistributorAccount { get; set; }
        public string DistributorPassword { get; set; }
    }
}
